INSERT INTO equipos VALUES('ALA', 'Deportivo Alavés SAD', 'Alavés', 'Vitoria/Gasteiz', 1, 1921, 17600);
INSERT INTO equipos VALUES('ATB', 'Athletic Club Bilbao', 'Athletic', 'Bilbao', 2, 1898, 44560);
INSERT INTO equipos VALUES('ATM', 'Cub Atlético de MAdrid S.A.D', 'Atlético de Madrd', 'Madrid', 3, 1903, 128249);
INSERT INTO equipos VALUES('BAR', 'Futbol Club Barcelona', 'Barcelona', 'Barcelona', 4, 1899, 144500);
INSERT INTO equipos VALUES('BET', 'Real Betis Balompié S.A.D', 'Betis', 'Sevilla', 5, 1907, 50373);
INSERT INTO equipos VALUES('CAD', 'Cádiz club de Fútbol S.A.D', 'Cádiz', 'Cádiz', 6, 1910, 15218);
INSERT INTO equipos VALUES('CEL', 'Real club Celta S.A.D', 'Celta', 'Vigo', 7, 1923, 16801);
INSERT INTO equipos VALUES('ELC', 'Elche club de Fútbol S.A.D', 'Elche', 'Elche', 8, 1922, 12005);
INSERT INTO equipos VALUES('ESP', 'Real club Deportivo Español de Barcelona S.A.D', 'Espanyol', 'Barcelona', 9, 1900, 22970);
INSERT INTO equipos VALUES('GET', 'Getafe club de Fúbol S.A.D', 'Getafe', 'Getafe', 10, 1923, 13000);
INSERT INTO equipos VALUES('GRA', 'Granada club de Fútbol S.A.D', 'Granada', 'Granada', 11, 1931, 13790);
INSERT INTO equipos VALUES('LEV', 'Levante Unión Deportiva S.A.D', 'Levante', 'Valencia', 12, 1909, 22589);
INSERT INTO equipos VALUES('MAL', 'Real club Deportivo Mallorca S.A.D', 'Mallorca', 'Palma de Mallorca', 13, 1916, 16125);
INSERT INTO equipos VALUES('OSA', 'Club Atlético Osasuna', 'Osasuna', 'Pamplona', 14, 1919, 15502);
INSERT INTO equipos VALUES('RSO', 'Real Sociedad de Fútbol S.A', 'Real Sociedad', 'San Sebastián', 17, 1909, 35342);
INSERT INTO equipos VALUES('RAY', 'Rayo Vallecano de Madrid S.A.D', 'Rao Vallecano', 'Vallecas, Madrid', 15, 1924, 10360);
INSERT INTO equipos VALUES('RMA', 'Real Madrid club de Fútbol', 'Real Madrid', 'Madrid', 16, 1902, 93176);
INSERT INTO equipos VALUES('SEV', 'Sevilla Fútbol club S.A.D', 'Sevilla', 'Sevilla', 18, 1890, 39955);
INSERT INTO equipos VALUES('VAL', 'Valencia club de Fútbol S.A.D', 'Valencia', 'Valencia', 19, 1923, 40000);
INSERT INTO equipos VALUES('VIL', 'Villarreal club de Fútbol S.A.D', 'Villarreal', 'Villarreal', 20, 1947, 15000);
INSERT INTO equipos VALUES('ALC', 'Agrupación Deportiva Alcorcón S.A.D', 'Alcorcón', 'Alcorcón', 21, 1971, 2500);
INSERT INTO equipos VALUES('ALM', 'Unión Deportiva Almería S.A.D', 'Almería', 'Almería', 22, 1989, 9000);
INSERT INTO equipos VALUES('BUR', 'Burgos club de Fútbol S.A.D', 'Burgos', 'Burgos', 23, 1922, 5000);
INSERT INTO equipos VALUES('CAR', 'Fútbol club Cartagena S.A.D', 'Cartagena', 'Cartagena', 24, 1995, 8200);
INSERT INTO equipos VALUES('EIB', 'Sociedad Deportiva Eibar S.A.D', 'Eibar', 'Eibar', 25, 1940, 5799);
INSERT INTO equipos VALUES('FUE', 'Club de Fútbol Fuenlabrada S.A.D', 'Fuenlabrada', 'Fuenlabrada', 26, 1975, 5000);
INSERT INTO equipos VALUES('GIR', 'Girona Fútbol club S.A.D', 'Girona', 'Girona', 27, 1930, 9501);
INSERT INTO equipos VALUES('HUE', 'Sociedad Deportiva Huesca S.A.D', 'Huesca', 'Huesca', 28, 1960, 6200);
INSERT INTO equipos VALUES('LPA', 'Unión Deportiva las Palmas S.A.D', 'Las Palmas', 'Las Palmas de Gran Canaria', 29, 1949, 12024);
INSERT INTO equipos VALUES('LEG', 'Club Deportivo Leganés S.A.D', 'Leganés', 'Leganés', 30, 1928, 10000);
INSERT INTO equipos VALUES('LUG', 'Club Deportivo Lugo S.A.D', 'Lugo', 'Lugo', 31, 1953, 3205);
INSERT INTO equipos VALUES('MIR', 'Club Deportivo Mirandés', 'Mirandés', 'Miranda de Ebro', 32, 1927, 3523);
INSERT INTO equipos VALUES('MAL', 'Málaga Club de Fútbol S.A.D', 'Málaga', 'Málaga', 33, 1948, 18000);
INSERT INTO equipos VALUES('OVI', 'Real Oviedo S.A.D', 'Oviedo', 'Oviedo', 34, 1926, 19000);
INSERT INTO equipos VALUES('PON', 'Sociedad Deportiva Ponferradina S.A.D', 'Ponferradina', 'Ponferrada', 35, 1922, 4500);
INSERT INTO equipos VALUES('RSB', 'Real Sociedad de Fútbol B', 'Real Sociedad B/Sanse', 'San Sebastián/Zubieta', 36, 1951, 35342);
INSERT INTO equipos VALUES('RVA', 'Real Valladolid club de Fútbol S.A.D', 'Valladolid', 'Valladolid', 37, 1928, 22004);
INSERT INTO equipos VALUES('ZAR', 'Real Zaragoza S.A.D', 'Zaragoza', 'Zaragoza', 38, 1932, 27500);
INSERT INTO equipos VALUES('AMO', 'Sociedad Deportiva Amorebieta', 'Amorebieta', 'Amorebieta-Echano', 39, 1925, 1000);
INSERT INTO equipos VALUES('SPO', 'Real Sporting de Gijón S.A.D', 'Sporting', 'Gijón', 40, 1905, 20000);
INSERT INTO equipos VALUES('TEN', 'Club Deportivo Tenerife S.A.D', 'Tenerife', 'Santa Cruz de Tenerife', 41, 1912, 11000);
INSERT INTO equipos VALUES('IBI', 'Unión Deportiva Ibiza S.A.D', 'Ibiza', 'Ibiza', 42, 2015, 1800);